import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'ko';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Nav
    'nav.home': '首页',
    'nav.services': '服务',
    'nav.products': '产品',
    'nav.global': '全球布局',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',

    // Hero
    'hero.label': '国际化服装供应链',
    'hero.line1': '从创意到成品',
    'hero.line2': '一站式柔性供应链',
    'hero.text': '专注冬装外套，整合全球优质资源，让每一个设计创意高效落地',
    'hero.sub': '专注冬装外套，整合全球优质资源，让每一个设计创意高效落地',
    'hero.cta1': '探索产品',
    'hero.cta2': '联系我们',

    // Products
    'products.label': '核心产品',
    'products.title': '专注冬装外套\n四大核心品类',
    'products.subtitle': '从基础款到高端定制，满足不同品牌的多样化需求',
    'products.down.title': '羽绒服 & 户外系列',
    'products.down.keyword': '复杂工艺 · 极致响应',
    'products.down.point1.title': '核心优势',
    'products.down.point1.desc': '20年经验版师团队，擅长制作结构复杂的专业滑雪服及功能性外衣。',
    'products.down.point2.title': '全球标准',
    'products.down.point2.desc': '整合中日顶级供应商，确保每一枚辅料均达奢品级标准。',
    'products.down.point3.title': '敏捷制造',
    'products.down.point3.desc': '极低MOQ（起订量），拥有不可复制的小单快反能力。',
    'products.down.tag1': '复杂工艺',
    'products.down.tag2': '极致响应',
    'products.coat.title': '双面羊绒大衣',
    'products.coat.keyword': '匠心手工 · 柔性供应',
    'products.coat.point1.title': '工艺标杆',
    'products.coat.point1.desc': '深耕20余年的匠人团队，缝制标准直达国际一线奢侈品级别。',
    'products.coat.point2.title': '快速反馈',
    'products.coat.point2.desc': '依托产业基地核心资源，各类面料打样实现全行业最快反馈。',
    'products.coat.point3.title': '灵活定制',
    'products.coat.point3.desc': '超低起订量与柔性周期，是设计师品牌落地的首选合作伙伴。',
    'products.coat.tag1': '匠心手工',
    'products.coat.tag2': '柔性供应',
    'products.fur.title': '皮草与皮毛一体',
    'products.fur.keyword': '产地根基 · 全球视野',
    'products.fur.point1.title': '产地优势',
    'products.fur.point1.desc': '根植中国海宁（全球最大皮草基地），拥有30年垂直领域深耕经验。',
    'products.fur.point2.title': '全能定制',
    'products.fur.point2.desc': '从原料搜源到设计开发，全方位满足品牌方对高端材质的需求。',
    'products.fur.point3.title': '库存无忧',
    'products.fur.point3.desc': '极具竞争力的灵活生产模式，让高端皮草品类不再有库存压力。',
    'products.fur.tag1': '产地根基',
    'products.fur.tag2': '全球视野',
    'products.duvet.title': '羽绒寝具',
    'products.duvet.keyword': '顶级填充 · 奢适体验',
    'products.duvet.point1.title': '全球选材',
    'products.duvet.point1.desc': '依托中国最大羽绒战略合作方，涵盖全球数十种高标准优质羽绒。',
    'products.duvet.point2.title': '私人方案',
    'products.duvet.point2.desc': '提供标准样件与高级私人定制，用技术面料重新定义睡眠美学。',
    'products.duvet.point3.title': '品质生活',
    'products.duvet.point3.desc': '极致的清洁度与蓬松度，专为追求生活质感的客户定制。',
    'products.duvet.tag1': '顶级填充',
    'products.duvet.tag2': '奢适体验',

    // Services
    'services.label': '全链路服务',
    'services.title': '从想法到成衣\n专业服务护航每一环',
    'services.subtitle': '六大核心服务，覆盖设计到交付的完整链路',
    'services.tagline': '让每一个灵感，精准落地成衣',
    'services.cta': '立即咨询',
    'services.design.title': '设计打样',
    'services.design.desc': '我们汇聚行业顶尖版师与工艺师，融合3D数字虚拟打样与实物样衣双轨制作体系，48小时内完成初版样衣，精准还原设计师每一处廓形细节与工艺要求，将创意以最高效率转化为可量产的成品方案',
    'services.design.point1.title': '3D虚拟打样',
    'services.design.point1.desc': '采用CLO3D等行业领先软件进行数字化建模，大幅缩短打样周期，降低物料浪费，支持远程实时审版',
    'services.design.point2.title': '实物样衣制作',
    'services.design.point2.desc': '资深版师全程把控，从坯布样到面料样逐步精修，确保每一道缝线、每一处结构均达到品牌交付标准',
    'services.design.point3.title': '工艺顾问支持',
    'services.design.point3.desc': '提供专属工艺顾问服务，协助品牌方优化设计细节，在保证美学的前提下提升生产可行性与成本效益',
    'services.design.tag1': '3D数字打样',
    'services.design.tag2': '48H极速响应',
    'services.sampling.title': '品牌孵化',
    'services.sampling.desc': '我们为新兴品牌及设计师提供从零到一的全链路孵化方案，涵盖品牌定位策划、商标注册、视觉识别系统设计、产品线规划、包装开发及多渠道销售推广，以专业资源矩阵助力品牌在最短时间内完成市场化落地',
    'services.sampling.point1.title': '品牌战略规划',
    'services.sampling.point1.desc': '深度调研目标市场与竞品格局，协助品牌完成精准定位、用户画像构建及差异化价值主张提炼',
    'services.sampling.point2.title': '视觉与包装设计',
    'services.sampling.point2.desc': '提供品牌LOGO、主视觉、吊牌、包装盒等全套视觉物料设计，确保品牌调性在每一个触点上高度统一',
    'services.sampling.point3.title': '渠道落地支持',
    'services.sampling.point3.desc': '对接国内外主流电商平台及买手店渠道，提供选品建议、上架运营及营销推广的专业指导',
    'services.sampling.tag1': '全链路孵化',
    'services.sampling.tag2': '品牌战略',
    'services.production.title': '柔性生产',
    'services.production.desc': '依托2000余家深度合作的精选工厂联盟，我们构建了业内领先的柔性生产体系，支持100件起订的小批量模式，标准款15–25天极速交付，并通过全链条数字化管理系统实现订单进度实时可视，让每一笔订单的生产状态尽在掌握',
    'services.production.point1.title': '小单快反能力',
    'services.production.point1.desc': '最低100件起订，打破传统工厂高MOQ壁垒，帮助品牌以最低库存风险验证市场，快速迭代产品',
    'services.production.point2.title': '精选工厂联盟',
    'services.production.point2.desc': '2000+家经严格资质审核的合作工厂，涵盖羽绒、大衣、皮草等细分品类，按订单需求智能匹配最优产能',
    'services.production.point3.title': '全程可视化管理',
    'services.production.point3.desc': '自主研发的订单追踪系统，从裁剪、缝制、后整到出货全流程节点实时上报，客户随时查看生产进度',
    'services.production.tag1': '100件起订',
    'services.production.tag2': '15–25天交付',
    'services.fabric.title': '面料采购',
    'services.fabric.desc': '我们与全球500余家顶级面料供应商建立长期战略合作，覆盖中日韩欧意等主要纺织产区，提供从面料研发、定制开发、小样打样到第三方检测认证的一站式服务，确保每一块面料均符合品牌的品质标准与可持续发展要求',
    'services.fabric.point1.title': '全球面料资源库',
    'services.fabric.point1.desc': '整合中国、日本、韩国、意大利等产地的顶级面料资源，涵盖羽绒面料、双面呢、皮草、功能性面料等数千个SKU',
    'services.fabric.point2.title': '定制开发服务',
    'services.fabric.point2.desc': '支持品牌独家面料开发，包括专属纱线配比、组织结构定制及特殊后整理工艺，打造无法复制的差异化面料竞争力',
    'services.fabric.point3.title': '检测与认证支持',
    'services.fabric.point3.desc': '与SGS、BV等国际权威检测机构合作，提供成分检测、色牢度、缩水率等全项目检测报告，满足全球市场准入要求',
    'services.fabric.tag1': '500+供应商',
    'services.fabric.tag2': '全球产地直采',
    'services.quality.title': '质量控制',
    'services.quality.desc': '我们建立了覆盖全生产链路的12道专项质检体系，从原材料入库验收、在制品过程检验到成品出货前终检，每一道工序均有专职QC人员把关，并通过数字化质检系统生成可追溯的质检报告，为每一件成品提供有据可查的品质背书',
    'services.quality.point1.title': '来料检验（IQC）',
    'services.quality.point1.desc': '对所有进厂原辅料进行严格的来料检验，包括面料色差、克重、成分及辅料规格，不合格物料一律拒绝入库',
    'services.quality.point2.title': '过程质控（IPQC）',
    'services.quality.point2.desc': '在裁剪、缝制、后整等关键工序设置质控节点，实时抽检，发现问题即时反馈产线整改，将不良品消灭在生产过程中',
    'services.quality.point3.title': '成品终检（FQC）',
    'services.quality.point3.desc': '出货前对成品进行全面终检，涵盖尺寸规格、外观工艺、包装标准等，并出具完整质检报告随货交付',
    'services.quality.tag1': '12道质检工序',
    'services.quality.tag2': '全程可追溯',
    'services.logistics.title': '物流配送',
    'services.logistics.desc': '我们提供端到端的国际物流解决方案，整合海运、空运、快递及海外本地配送等多种运输方式，并与DHL、FedEx等国际头部物流商建立优先合作，支持多目的地拆分发货，通过自研物流追踪平台实现订单状态全程实时可视',
    'services.logistics.point1.title': '多式联运方案',
    'services.logistics.point1.desc': '根据订单时效与成本需求，智能匹配海运整柜/拼箱、空运及快递等最优运输组合，覆盖全球主要目的地港口',
    'services.logistics.point2.title': '海外仓储支持',
    'services.logistics.point2.desc': '在韩国首尔设有自营仓储中心，支持本地分拨、退换货处理及跨境电商履约，有效降低末端配送成本',
    'services.logistics.point3.title': '实时追踪系统',
    'services.logistics.point3.desc': '自研物流可视化平台，从工厂出货到客户签收全链路节点实时更新，支持多语言通知，让客户随时掌握货物动态',
    'services.logistics.tag1': '全球多式联运',
    'services.logistics.tag2': '实时可视追踪',

    // Global Presence
    'global.label': '全球布局',
    'global.title': '立足杭州\n首尔为首个海外分部',
    'global.subtitle': '国际化运营，本地化服务',
    'global.hq': '总部',
    'global.branch': '海外分部',
    'global.label': '全球布局',
    'global.title': '立足杭州 首尔为首个海外分部',
    'global.subtitle': '国际化运营，本地化服务',
    'global.hangzhou': '杭州',
    'global.seoul': '首尔',
    'global.hz.status': '中国总部',
    'global.kr.status': '韩国分部',
    'global.hz.desc': '中国服装供应链核心枢纽，整合长三角优质制造资源',
    'global.kr.desc': '韩国时尚之都，连接东亚顶级设计师与品牌资源',
    'global.hangzhou.city': '杭州',
    'global.hangzhou.desc': '中国服装供应链核心枢纽，整合长三角优质制造资源',
    'global.seoul.city': '首尔',
    'global.seoul.desc': '韩国时尚之都，连接东亚顶级设计师与品牌资源',
    'global.expanding': '即将进驻',
    'global.tokyo': '东京',
    'global.paris': '巴黎',
    'global.newyork': '纽约',
    'global.milan': '米兰',
    'global.address': '地址',
    'global.phone': '电话',
    'global.email': '邮箱',
    'global.hours': '时间',
    'global.upcoming': '即将进驻',

    // About
    'about.label': '关于我们',
    'about.title': '我们是谁',
    'about.subtitle': '国际化服装供应链的创新者',
    'about.story.title': '重新定义服装供应链：SAMPLE & SIMPLE',
    'about.story.text': '我们诞生于对时尚与卓越制造的极致追求。为了打破传统供应链对设计的局限，我们构建了一个连接创意与生产的全球化柔性平台，致力于将供应链的灵活性转化为品牌的差异化核心价值。\n\n平台深度整合首尔分部的时尚策源能力与杭州供应链总部的制造实力，专注于羽绒服、双面呢大衣及高端皮草的全案服务。通过连接中日韩顶级面辅料资源，我们实现了100件起订的友好量产模式，以极致的"小单快反"最大程度降低品牌的库存与销售压力。\n\n从精准打样到规模量产，我们全程严控品质标准，为全球中高端品牌提供一站式 JDM 解决方案。我们以极强的跨国响应能力，助力每一个品牌将灵感完美落地，实现卓越成长。',
    'about.brand.hz': 'RONDA — 杭州',
    'about.brand.kr': 'ATLY — 首尔',
    'about.digital': '数字化驱动',
    'about.digital.desc': '全链条数字化管理，实时可视化每一个订单的生产进度',
    'about.talent': '顶尖人才',
    'about.talent.desc': '汇聚服装、供应链、设计领域的资深专业人才',
    'about.global': '全球视野',
    'about.global.desc': '立足杭州，布局首尔，连接全球优质资源与市场',
    'about.sustainable': '可持续发展',
    'about.sustainable.desc': '推动绿色面料与可持续生产工艺，助力品牌ESG建设',
    'stats.years': '年行业经验',
    'stats.years.val': '10+',
    'stats.years.unit': '年行业经验',
    'stats.factories': '合作工厂',
    'stats.factories.val': '2000+',
    'stats.fabrics': '面料供应商',
    'stats.fabrics.val': '500+',
    'stats.moq': '起订量',
    'stats.moq.val': '100件',
    'stats.team': '专业团队',
    'stats.team.unit': '人',
    'stats.output': '年产能',
    'stats.output.unit': '万件',
    'stats.countries': '覆盖国家',
    'stats.countries.unit': '个',

    // Contact
    'contact.label': '联系我们',
    'contact.title': '无论您在全球哪个角落\n我们都在这里',
    'contact.subtitle': '随时欢迎您的咨询',
    'contact.hangzhou': '杭州总部 · RONDA',
    'contact.seoul': '首尔分部 · ATLY',
    'contact.hz.phone': '0571-88012309',
    'contact.hz.email': 'zylen@samplewear.com',
    'contact.hz.address': '杭州市西湖区瑞博国际B座1707',
    'contact.hz.time': '周一至周五 9:00–18:00',
    'contact.hz.hours': '周一至周五 9:00–18:00',
    'contact.kr.phone': '02 6956 9855',
    'contact.kr.email1': 'kimsih6068@naver.com',
    'contact.kr.email2': 'guangmdc0901@gmail.com',
    'contact.kr.address': '5F, Jeongha Building, 174 Donggyo-dong, Mapo-gu, Seoul',
    'contact.kr.time': '周一至周五 9:00–18:00',
    'contact.kr.hours': '周一至周五 9:00–18:00',
    'contact.form.name': '姓名',
    'contact.form.phone': '电话',
    'contact.form.email': '邮箱',
    'contact.form.service': '服务类型',
    'contact.form.service.placeholder': '请选择服务类型',
    'contact.form.service.down': '羽绒服定制',
    'contact.form.service.coat': '大衣定制',
    'contact.form.service.fur': '皮草定制',
    'contact.form.service.duvet': '羽绒被定制',
    'contact.form.service.other': '其他',
    'contact.form.message': '请详细描述您的需求...',
    'contact.form.submit': '提交咨询',
    'contact.form.sent': '已收到您的咨询，我们将尽快与您联系！',
    'contact.social.title': '社交媒体',
    'contact.im.title': '即时通讯',
    'contact.scan': '扫码关注',
    'contact.click': '点击联系',

    // Footer
    'footer.tagline': '国际化服装供应链平台',
    'footer.rights': '© 2025 Sample & Simple. 保留所有权利.',
    'footer.privacy': '隐私政策',
    'footer.nav.products': '产品',
    'footer.nav.services': '服务',
    'footer.nav.global': '全球布局',
    'footer.nav.about': '关于我们',
    'footer.nav.contact': '联系我们',
    'footer.offices': '全球办公室',
    'footer.company.label': '公司信息',
    'footer.company.name': '杭州绒达科技有限公司',
    'footer.nav.label': '导航',
    'footer.follow': '关注我们',
    'footer.terms': '服务条款',
    'footer.icp': '浙ICP备2025188038号-1',
    // Sample App Section
    'sampleapp.label': '数字化平台',
    'sampleapp.title': '全球领先的冬装数字化供应链平台',
    'sampleapp.slogan': '更简单 · 更方便 · 更准确',
    'sampleapp.availability': 'Sample App 目前已在中国区上架，全球版本即将陆续登陆各大应用商店',
    'sampleapp.slide1.title': '我们的定位',
    'sampleapp.slide1.subtitle': '连接全球创意与中国顶尖制造的数字化桥梁',
    'sampleapp.slide1.desc': 'Sample 专注于中高端冬装（羽绒服、双面呢、皮草）的一站式定制服务，让独立设计师与品牌主跨越国界，在办公室即可完成从样衣开发到大货交付的全流程。',
    'sampleapp.slide1.tag1': '100件起订',
    'sampleapp.slide1.tag2': '全流程数字化',
    'sampleapp.slide2.title': '全链路透明',
    'sampleapp.slide2.subtitle': '数字化进度追踪，彻底告别沟通盲区',
    'sampleapp.slide2.desc': '从样衣完成生产、物流信息上传到确认收货，每一个节点实时同步。跨境物流全程可视化，订单状态一目了然，让您足不出户掌控每一笔订单。',
    'sampleapp.slide2.tag1': '实时追踪',
    'sampleapp.slide2.tag2': '跨境物流同步',
    'sampleapp.slide3.title': '汇报周期',
    'sampleapp.slide3.subtitle': '生产进度实时汇报，透明可控',
    'sampleapp.slide3.desc': '工厂按材料到齐、样衣制作、完成生产三大节点上传进度图片，每一步骤有据可查。引入第三方专业质检与订单保险系统，确保跨国贸易的安全与品质，让每一笔订单都有保障。',
    'sampleapp.slide3.tag1': '质检保障',
    'sampleapp.slide3.tag2': '订单保险',
    'sampleapp.slide4.title': '在线定制',
    'sampleapp.slide4.subtitle': '四步完成样衣定制，专业高效',
    'sampleapp.slide4.desc': '款式类型、样衣正反、面料辅料、数量配置——四步引导式流程，让您轻松完成专业样衣定制。上传参考图片，填写改款需求，平台自动匹配最优工厂资源。',
    'sampleapp.slide4.tag1': '四步定制',
    'sampleapp.slide4.tag2': 'AI智能匹配',
    'sampleapp.slide5.title': '个人工作台',
    'sampleapp.slide5.subtitle': '样衣方案、订单管理、企业认证一站搞定',
    'sampleapp.slide5.desc': '个人工作台集成样衣方案、样衣订单、批量订单三大模块，支持企业认证与发票管理。认证用户享有专属客服与优先排产权益，全面提升采购效率。',
    'sampleapp.slide5.tag1': '企业认证',
    'sampleapp.slide5.tag2': '专属客服',
    'sampleapp.feature1.icon': '⬡',
    'sampleapp.feature1.title': '极简起订',
    'sampleapp.feature1.desc': '100件起订，小单快反，零库存压力验证市场',
    'sampleapp.feature2.icon': '◎',
    'sampleapp.feature2.title': '全程追踪',
    'sampleapp.feature2.desc': '数字化进度看板，每一节点实时可视',
    'sampleapp.feature3.icon': '◈',
    'sampleapp.feature3.title': '安全交付',
    'sampleapp.feature3.desc': '第三方质检 + 订单保险，跨境无忧',
    'sampleapp.ai.label': 'THE FUTURE IS AI',
    'sampleapp.ai.title': 'AI 驱动的数字化蓝图',
    'sampleapp.ai.point1': 'AI 辅助设计 — 即将推出 AI 趋势分析与设计生成工具，将创意转化为生产力',
    'sampleapp.ai.point2': '3D 虚拟试穿 — 研发 AI 建模技术，实现高仿真线上试穿，极大缩减物理打样周期与成本',
    'sampleapp.ai.point3': '全球协同 — 构建专属定制数据库，实现"设计在全球，制造在中国，服务于世界"的无界协作模式',

    // Inquiry Form
    'inquiry.title': 'INQUIRY',
    'inquiry.heading': '样品 & 订单咨询',
    'inquiry.subheading': '请填写以下信息，我们将在 1-2 个工作日内与您联系。',
    'inquiry.back': '返回首页',
    'inquiry.sampleType': '样衣类型',
    'inquiry.hasSample': '是否有参考样品',
    'inquiry.expectedQty': '预期订单数量',
    'inquiry.color': '颜色要求',
    'inquiry.size': '尺码范围',
    'inquiry.region': '所在地区',
    'inquiry.brand': '品牌名称',
    'inquiry.contact': '联系方式',
    'inquiry.message': '补充说明',
    'inquiry.select': '请选择',
    'inquiry.yes': '有',
    'inquiry.no': '无',
    'inquiry.qtyPlaceholder': '例：100件（最低起订量）',
    'inquiry.colorPlaceholder': '例：米白色、黑色、深蓝色',
    'inquiry.sizePlaceholder': '例：S / M / L / XL（亚洲码）',
    'inquiry.regionPlaceholder': '例：中国大陆、韩国、欧洲',
    'inquiry.brandPlaceholder': '例：您的品牌名称或个人设计师',
    'inquiry.contactPlaceholder': '例：+86 138 0000 0000 或 email@example.com',
    'inquiry.messagePlaceholder': '请描述您的具体需求、面料偏好或其他特殊要求…',
    'inquiry.submit': '发送咨询',
    'inquiry.sending': '发送中…',
    'inquiry.success.title': '感谢您的咨询',
    'inquiry.success.desc': '我们已收到您的需求，将在 1-2 个工作日内与您联系。',
    'inquiry.error': '提交失败，请稍后重试。',
  },

  en: {
    // Nav
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.global': 'Global',
    'nav.about': 'About',
    'nav.contact': 'Contact',

    // Hero
    'hero.label': 'Global Apparel Supply Chain',
    'hero.line1': 'From Concept to Creation',
    'hero.line2': 'Flexible Supply Chain',
    'hero.text': '专注冬装外套，整合全球优质资源，让每一个设计创意高效落地',
    'hero.text': 'Specializing in winter outerwear — integrating global premium resources to bring every design vision to life',
    'hero.sub': 'Specializing in winter outerwear — integrating global premium resources to bring every design vision to life',
    'hero.cta1': 'Explore Products',
    'hero.cta2': 'Contact Us',

    // Products
    'products.label': 'Core Products',
    'products.title': 'Winter Outerwear\nFour Core Categories',
    'products.subtitle': 'From essentials to bespoke — meeting the diverse needs of every brand',
    'products.down.title': 'Down Jackets & Outdoor Series',
    'products.down.keyword': 'Complex Craftsmanship · Rapid Response',
    'products.down.point1.title': 'Core Strength',
    'products.down.point1.desc': 'A team of pattern masters with 20 years of experience, specializing in technically complex ski wear and functional outerwear.',
    'products.down.point2.title': 'Global Standards',
    'products.down.point2.desc': 'Integrating top-tier suppliers from China and Japan to ensure every trim meets luxury-grade standards.',
    'products.down.point3.title': 'Agile Manufacturing',
    'products.down.point3.desc': 'Ultra-low MOQ with an unmatched small-batch, fast-turnaround capability.',
    'products.down.tag1': 'Complex Craft',
    'products.down.tag2': 'Rapid Response',
    'products.coat.title': 'Double-Faced Cashmere Coats',
    'products.coat.keyword': 'Artisan Craftsmanship · Flexible Supply',
    'products.coat.point1.title': 'Craft Benchmark',
    'products.coat.point1.desc': 'An artisan team with 20+ years of expertise, with stitching standards matching international luxury houses.',
    'products.coat.point2.title': 'Fast Feedback',
    'products.coat.point2.desc': 'Leveraging core industrial base resources for the fastest fabric sampling turnaround in the industry.',
    'products.coat.point3.title': 'Flexible Customization',
    'products.coat.point3.desc': 'Ultra-low MOQ and flexible lead times — the preferred partner for designer brands to bring ideas to life.',
    'products.coat.tag1': 'Artisan Craft',
    'products.coat.tag2': 'Flexible Supply',
    'products.fur.title': 'Fur & Shearling',
    'products.fur.keyword': 'Origin Roots · Global Vision',
    'products.fur.point1.title': 'Origin Advantage',
    'products.fur.point1.desc': "Rooted in Haining, China (the world's largest fur base), with 30 years of vertical domain expertise.",
    'products.fur.point2.title': 'Full Customization',
    'products.fur.point2.desc': "From raw material sourcing to design development — meeting every brand's demand for premium materials.",
    'products.fur.point3.title': 'Zero Inventory Pressure',
    'products.fur.point3.desc': 'A highly competitive flexible production model that eliminates inventory risk for premium fur categories.',
    'products.fur.tag1': 'Origin Roots',
    'products.fur.tag2': 'Global Vision',
    'products.duvet.title': 'Down Bedding',
    'products.duvet.keyword': 'Premium Fill · Luxurious Comfort',
    'products.duvet.point1.title': 'Global Sourcing',
    'products.duvet.point1.desc': "Backed by China's largest down strategic partner, covering dozens of high-standard premium down varieties worldwide.",
    'products.duvet.point2.title': 'Private Solutions',
    'products.duvet.point2.desc': 'Offering standard samples and bespoke private label options — redefining sleep aesthetics with technical fabrics.',
    'products.duvet.point3.title': 'Quality Living',
    'products.duvet.point3.desc': 'Ultimate cleanliness and loft, crafted for clients who demand the finest in everyday living.',
    'products.duvet.tag1': 'Premium Fill',
    'products.duvet.tag2': 'Luxurious Comfort',

    // Services
    'services.label': 'Full-Chain Services',
    'services.title': 'From Idea to Garment\nEvery Step Covered',
    'services.subtitle': 'Six core services covering the complete chain from design to delivery',
    'services.tagline': 'Every idea, perfectly realized in fabric',
    'services.cta': 'Inquire Now',
    'services.design.title': 'Design & Sampling',
    'services.design.desc': 'Our elite team of pattern masters and craftspeople operates a dual-track system combining 3D digital virtual sampling with physical prototype production. Initial samples are completed within 48 hours, faithfully reproducing every silhouette detail and construction requirement, converting creative vision into production-ready solutions with maximum efficiency.',
    'services.design.point1.title': '3D Virtual Sampling',
    'services.design.point1.desc': 'Leveraging industry-leading software such as CLO3D for digital modeling, significantly reducing sampling lead times, minimizing material waste, and enabling real-time remote review and approval.',
    'services.design.point2.title': 'Physical Prototype Production',
    'services.design.point2.desc': 'Senior pattern masters oversee every stage, from muslin toile to final fabric sample, progressively refining each stitch and structural element to meet the brand\'s exacting delivery standards.',
    'services.design.point3.title': 'Technical Advisory Support',
    'services.design.point3.desc': 'Dedicated technical advisors collaborate with brands to optimize design details, enhancing production feasibility and cost efficiency while preserving the intended aesthetic vision.',
    'services.design.tag1': '3D Digital Sampling',
    'services.design.tag2': '48H Rapid Response',
    'services.sampling.title': 'Brand Incubation',
    'services.sampling.desc': 'We provide emerging brands and designers with comprehensive end-to-end incubation solutions, encompassing brand positioning strategy, trademark registration, visual identity system design, product line planning, packaging development, and multi-channel sales promotion, leveraging our professional resource network to achieve market-ready launch in the shortest possible timeframe.',
    'services.sampling.point1.title': 'Brand Strategy Planning',
    'services.sampling.point1.desc': 'In-depth research into target markets and competitive landscapes, assisting brands in establishing precise positioning, constructing user personas, and articulating differentiated value propositions.',
    'services.sampling.point2.title': 'Visual & Packaging Design',
    'services.sampling.point2.desc': 'Full suite of visual asset design including brand logo, key visuals, hangtags, and packaging, ensuring consistent brand tonality across every consumer touchpoint.',
    'services.sampling.point3.title': 'Channel Launch Support',
    'services.sampling.point3.desc': 'Connecting brands with leading domestic and international e-commerce platforms and buyer channels, providing professional guidance on product selection, store operations, and marketing campaigns.',
    'services.sampling.tag1': 'Full-Chain Incubation',
    'services.sampling.tag2': 'Brand Strategy',
    'services.production.title': 'Flexible Manufacturing',
    'services.production.desc': 'Backed by an alliance of 2000+ rigorously vetted manufacturing partners, we have built an industry-leading flexible production system supporting small-batch orders from 100 pieces. Standard styles are delivered in 15–25 days, with full-chain digital management enabling real-time order visibility, ensuring complete transparency over every production milestone.',
    'services.production.point1.title': 'Small-Batch Agility',
    'services.production.point1.desc': 'Minimum order of 100 pieces breaks through the high-MOQ barrier of traditional factories, enabling brands to validate markets with minimal inventory risk and rapidly iterate on product lines.',
    'services.production.point2.title': 'Curated Factory Alliance',
    'services.production.point2.desc': '2000+ partner factories, each passing stringent qualification audits, covering down, outerwear, and fur sub-categories, intelligently matched to each order\'s specific capacity requirements.',
    'services.production.point3.title': 'Full-Chain Visual Management',
    'services.production.point3.desc': 'Proprietary order tracking system with real-time reporting at every production node — from cutting and sewing to finishing and dispatch — allowing clients to monitor progress at any time.',
    'services.production.tag1': 'From 100 pcs MOQ',
    'services.production.tag2': '15–25 Day Delivery',
    'services.fabric.title': 'Fabric Procurement',
    'services.fabric.desc': 'We maintain long-term strategic partnerships with over 500 world-class fabric suppliers across China, Japan, Korea, Europe, and Italy, covering all major textile-producing regions. Our one-stop service spans fabric R&D, bespoke development, sample production, and third-party testing certification, ensuring every material meets the brand\'s quality benchmarks and sustainability commitments.',
    'services.fabric.point1.title': 'Global Fabric Library',
    'services.fabric.point1.desc': 'Aggregating premium fabric resources from China, Japan, Korea, and Italy, covering thousands of SKUs including down fabrics, double-faced cashmere, fur, and performance materials.',
    'services.fabric.point2.title': 'Bespoke Development',
    'services.fabric.point2.desc': 'Supporting exclusive fabric development for brands, including proprietary yarn compositions, custom weave structures, and special finishing processes to create unrivaled material differentiation.',
    'services.fabric.point3.title': 'Testing & Certification',
    'services.fabric.point3.desc': 'Partnering with internationally accredited testing bodies including SGS and Bureau Veritas, providing comprehensive reports on fiber content, colorfastness, shrinkage, and more to meet global market entry requirements.',
    'services.fabric.tag1': '500+ Suppliers',
    'services.fabric.tag2': 'Direct Global Sourcing',
    'services.quality.title': 'Quality Assurance',
    'services.quality.desc': 'We have established a 12-point quality inspection system spanning the entire production chain, from incoming raw material inspection and in-process quality control to final pre-shipment inspection. Each stage is overseen by dedicated QC personnel, with a digitalized quality management system generating fully traceable inspection reports, providing verifiable quality assurance for every finished garment.',
    'services.quality.point1.title': 'Incoming Quality Control (IQC)',
    'services.quality.point1.desc': 'Rigorous inspection of all incoming raw materials and trims, including fabric shade variation, weight, fiber content, and accessory specifications; non-conforming materials are rejected without exception.',
    'services.quality.point2.title': 'In-Process Quality Control (IPQC)',
    'services.quality.point2.desc': 'Quality control checkpoints at critical production stages including cutting, sewing, and finishing, with real-time sampling and immediate corrective action to eliminate defects within the production process.',
    'services.quality.point3.title': 'Final Quality Control (FQC)',
    'services.quality.point3.desc': 'Comprehensive pre-shipment inspection covering dimensional specifications, workmanship appearance, and packaging standards, with a complete inspection report delivered alongside each shipment.',
    'services.quality.tag1': '12-Point Inspection',
    'services.quality.tag2': 'Full Traceability',
    'services.logistics.title': 'Logistics & Delivery',
    'services.logistics.desc': 'We provide end-to-end international logistics solutions, integrating sea freight, air freight, express delivery, and local last-mile distribution. Priority partnerships with DHL, FedEx, and other leading global carriers support multi-destination split shipments, while our proprietary logistics tracking platform delivers real-time, full-chain order visibility from factory dispatch to client receipt.',
    'services.logistics.point1.title': 'Multi-Modal Transport',
    'services.logistics.point1.desc': 'Intelligent matching of FCL/LCL sea freight, air freight, and express delivery based on order lead time and cost requirements, covering all major destination ports worldwide.',
    'services.logistics.point2.title': 'Overseas Warehousing',
    'services.logistics.point2.desc': 'Proprietary warehousing center in Seoul, Korea, supporting local distribution, returns processing, and cross-border e-commerce fulfillment to effectively reduce last-mile delivery costs.',
    'services.logistics.point3.title': 'Real-Time Tracking Platform',
    'services.logistics.point3.desc': 'Proprietary logistics visualization platform with real-time updates at every chain node from factory dispatch to client sign-off, supporting multilingual notifications for full cargo visibility.',
    'services.logistics.tag1': 'Global Multi-Modal',
    'services.logistics.tag2': 'Real-Time Tracking',

    // Global Presence
    'global.label': 'Global Presence',
    'global.title': 'Rooted in Hangzhou\nSeoul as First International Branch',
    'global.subtitle': 'International operations, localized service',
    'global.hq': 'Headquarters',
    'global.branch': 'International Branch',
    'global.label': '全球布局',
    'global.title': '立足杭州 首尔为首个海外分部',
    'global.subtitle': '国际化运营，本地化服务',
    'global.hangzhou': '杭州',
    'global.seoul': '首尔',
    'global.hz.status': '中国总部',
    'global.kr.status': '韩国分部',
    'global.hz.desc': '中国服装供应链核心枢纽，整合长三角优质制造资源',
    'global.kr.desc': '韩国时尚之都，连接东亚顶级设计师与品牌资源',
    'global.hangzhou.city': 'Hangzhou',
    'global.hangzhou.desc': 'Core hub of China\'s apparel supply chain, integrating premium manufacturing resources across the Yangtze River Delta',
    'global.seoul.city': 'Seoul',
    'global.seoul.desc': 'Fashion capital of Korea, connecting top East Asian designers and brand resources',
    'global.expanding': 'Coming Soon',
    'global.tokyo': 'Tokyo',
    'global.paris': 'Paris',
    'global.newyork': 'New York',
    'global.milan': 'Milan',
    'global.address': 'Address',
    'global.phone': 'Phone',
    'global.email': 'Email',
    'global.hours': 'Hours',
    'global.upcoming': 'Coming Soon',

    // About
    'about.label': 'About Us',
    'about.title': 'Who We Are',
    'about.subtitle': 'Innovators in global apparel supply chain',
    'about.story.title': 'Redefining the Apparel Supply Chain: SAMPLE & SIMPLE',
    'about.story.text': 'We were born from an uncompromising pursuit of fashion and manufacturing excellence. To break the constraints that traditional supply chains impose on design, we built a global flexible platform connecting creativity with production — dedicated to transforming supply chain agility into a brand\'s core differentiator.\n\nThe platform deeply integrates the fashion-sourcing capabilities of our Seoul office with the manufacturing strength of our Hangzhou supply chain headquarters, specializing in full-service solutions for down jackets, double-faced wool coats, and premium shearling. By connecting top-tier fabric and accessory resources across China, Japan, and Korea, we enable a friendly MOQ of 100 pieces — maximizing the "small-batch, fast-response" model to minimize inventory and sales pressure for brands.\n\nFrom precision sampling to scaled production, we maintain rigorous quality standards throughout, delivering one-stop JDM solutions for premium and luxury brands worldwide. With exceptional cross-border responsiveness, we help every brand bring their vision to life — and achieve outstanding growth.',
    'about.brand.hz': 'RONDA — Hangzhou',
    'about.brand.kr': 'ATLY — Seoul',
    'about.digital': 'Digital-First',
    'about.digital.desc': 'Full-chain digital management with real-time visibility into every order\'s production status',
    'about.talent': 'Top Talent',
    'about.talent.desc': 'Bringing together seasoned professionals in fashion, supply chain, and design',
    'about.global': 'Global Vision',
    'about.global.desc': 'Based in Hangzhou, expanding to Seoul, connecting global premium resources and markets',
    'about.sustainable': 'Sustainability',
    'about.sustainable.desc': 'Championing eco-friendly fabrics and sustainable production practices for brand ESG goals',
    'stats.years': 'Years Experience',
    'stats.years.val': '10+',
    'stats.years.unit': 'Years',
    'stats.factories': 'Partner Factories',
    'stats.factories.val': '2000+',
    'stats.fabrics': 'Fabric Suppliers',
    'stats.fabrics.val': '500+',
    'stats.moq': 'Min. Order Qty',
    'stats.moq.val': '100 pcs',
    'stats.team': 'Team Members',
    'stats.team.unit': 'pcs',
    'stats.output': 'Annual Output',
    'stats.output.unit': 'K pcs',
    'stats.countries': 'Countries',
    'stats.countries.unit': '+',

    // Contact
    'contact.label': 'Contact Us',
    'contact.title': 'Wherever You Are\nWe Are Here',
    'contact.subtitle': 'Your inquiry is always welcome',
    'contact.hangzhou': 'Hangzhou HQ · RONDA',
    'contact.seoul': 'Seoul Office · ATLY',
    'contact.hz.phone': '0571-88012309',
    'contact.hz.email': 'zylen@samplewear.com',
    'contact.hz.address': 'Room 1707, Ruibo International Building B, Xihu District, Hangzhou',
    'contact.hz.time': 'Mon–Fri 9:00–18:00',
    'contact.hz.hours': 'Mon–Fri 9:00–18:00',
    'contact.kr.phone': '02 6956 9855',
    'contact.kr.email1': 'kimsih6068@naver.com',
    'contact.kr.email2': 'guangmdc0901@gmail.com',
    'contact.kr.address': '5F, Jeongha Building, 174 Donggyo-dong, Mapo-gu, Seoul',
    'contact.kr.time': 'Mon–Fri 9:00–18:00',
    'contact.kr.hours': 'Mon–Fri 9:00–18:00',
    'contact.form.name': 'Full Name',
    'contact.form.phone': 'Phone',
    'contact.form.email': 'Email',
    'contact.form.service': 'Service Type',
    'contact.form.service.placeholder': 'Select a service',
    'contact.form.service.down': 'Down Jacket Custom',
    'contact.form.service.coat': 'Coat Custom',
    'contact.form.service.fur': 'Shearling Custom',
    'contact.form.service.duvet': 'Down Duvet Custom',
    'contact.form.service.other': 'Other',
    'contact.form.message': 'Please describe your requirements in detail...',
    'contact.form.submit': 'Submit Inquiry',
    'contact.form.sent': 'Received! We will get back to you shortly.',
    'contact.social.title': 'Social Media',
    'contact.im.title': 'Instant Messaging',
    'contact.scan': 'Scan to Follow',
    'contact.click': 'Click to Connect',

    // Footer
    'footer.tagline': 'Global Apparel Supply Chain Platform',
    'footer.rights': '© 2025 Sample & Simple. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.nav.products': 'Products',
    'footer.nav.services': 'Services',
    'footer.nav.global': 'Global',
    'footer.nav.about': 'About',
    'footer.nav.contact': 'Contact',
    'footer.offices': 'Global Offices',
    'footer.company.label': 'Company',
    'footer.company.name': 'Hangzhou Rongda Technology Co., Ltd.',
    'footer.nav.label': 'Navigation',
    'footer.follow': 'Follow Us',
    'footer.terms': 'Terms of Service',
    'footer.icp': '浙ICP备2025188038号-1',
    // Sample App Section
    'sampleapp.label': 'Digital Platform',
    'sampleapp.title': "The World's Leading Digital Supply Chain Platform for Winter Apparel",
    'sampleapp.slogan': 'Simpler · Smarter · More Accurate',
    'sampleapp.availability': 'Sample App is now available in China. Global version coming soon to all major app stores.',
    'sampleapp.slide1.title': 'Our Positioning',
    'sampleapp.slide1.subtitle': "The digital bridge connecting global creativity with China's finest manufacturing",
    'sampleapp.slide1.desc': 'Sample specializes in one-stop customization for premium winter apparel — down jackets, double-faced coats, and fur. Independent designers and brand owners can complete the entire process from sample development to bulk delivery, all from their office.',
    'sampleapp.slide1.tag1': 'MOQ 100 pcs',
    'sampleapp.slide1.tag2': 'End-to-End Digital',
    'sampleapp.slide2.title': 'Full Transparency',
    'sampleapp.slide2.subtitle': 'Digital progress tracking — no more communication blind spots',
    'sampleapp.slide2.desc': 'From sample production completion and logistics upload to delivery confirmation, every milestone syncs in real time. Full visibility on cross-border logistics keeps you in control of every order, wherever you are.',
    'sampleapp.slide2.tag1': 'Real-Time Tracking',
    'sampleapp.slide2.tag2': 'Cross-Border Sync',
    'sampleapp.slide3.title': 'Progress Reports',
    'sampleapp.slide3.subtitle': 'Real-time production updates, transparent and accountable',
    'sampleapp.slide3.desc': 'Factories upload progress photos at three key milestones: materials ready, sample production, and completion. Every step is documented. Third-party quality inspection and order insurance ensure the safety and quality of every cross-border transaction.',
    'sampleapp.slide3.tag1': 'QC Guarantee',
    'sampleapp.slide3.tag2': 'Order Insurance',
    'sampleapp.slide4.title': 'Online Customization',
    'sampleapp.slide4.subtitle': 'Four steps to complete sample customization, professional and efficient',
    'sampleapp.slide4.desc': 'Style type, sample front/back, fabric & accessories, quantity — a guided four-step process that makes professional sample customization effortless. Upload reference images, specify modifications, and the platform automatically matches the best factory resources.',
    'sampleapp.slide4.tag1': '4-Step Process',
    'sampleapp.slide4.tag2': 'AI Smart Matching',
    'sampleapp.slide5.title': 'Personal Dashboard',
    'sampleapp.slide5.subtitle': 'Sample plans, order management, and business verification — all in one place',
    'sampleapp.slide5.desc': 'The personal dashboard integrates three modules: sample plans, sample orders, and bulk orders, with support for business verification and invoice management. Verified users enjoy dedicated customer service and priority production scheduling.',
    'sampleapp.slide5.tag1': 'Business Verified',
    'sampleapp.slide5.tag2': 'Dedicated Support',
    'sampleapp.feature1.icon': '⬡',
    'sampleapp.feature1.title': 'Low MOQ',
    'sampleapp.feature1.desc': 'Start from 100 pcs, fast turnaround, zero inventory risk',
    'sampleapp.feature2.icon': '◎',
    'sampleapp.feature2.title': 'Full Tracking',
    'sampleapp.feature2.desc': 'Digital dashboard with real-time visibility at every milestone',
    'sampleapp.feature3.icon': '◈',
    'sampleapp.feature3.title': 'Secure Delivery',
    'sampleapp.feature3.desc': '3rd-party QC + order insurance for worry-free cross-border trade',
    'sampleapp.ai.label': 'THE FUTURE IS AI',
    'sampleapp.ai.title': 'Our AI-Driven Digital Vision',
    'sampleapp.ai.point1': 'AI-Assisted Design — Launching AI trend analysis and design generation tools to turn creativity into production power',
    'sampleapp.ai.point2': '3D Virtual Try-On — Developing AI modeling technology for high-fidelity online fitting, dramatically reducing physical sampling cycles and costs',
    'sampleapp.ai.point3': 'Global Collaboration — Building a proprietary customization database to enable borderless collaboration: design globally, manufacture in China, serve the world',
    // Inquiry Form
    'inquiry.title': 'INQUIRY',
    'inquiry.heading': 'Sample & Order Inquiry',
    'inquiry.subheading': 'Fill in the details below and we will get back to you within 1-2 business days.',
    'inquiry.back': 'Back to Home',
    'inquiry.sampleType': 'Sample Type',
    'inquiry.hasSample': 'Do you have a reference sample?',
    'inquiry.expectedQty': 'Expected Order Quantity',
    'inquiry.color': 'Color Requirements',
    'inquiry.size': 'Size Range',
    'inquiry.region': 'Your Region',
    'inquiry.brand': 'Brand Name',
    'inquiry.contact': 'Contact Info',
    'inquiry.message': 'Additional Notes',
    'inquiry.select': 'Please select',
    'inquiry.yes': 'Yes',
    'inquiry.no': 'No',
    'inquiry.qtyPlaceholder': 'e.g. 100 pcs (minimum order)',
    'inquiry.colorPlaceholder': 'e.g. Off-white, Black, Navy Blue',
    'inquiry.sizePlaceholder': 'e.g. XS / S / M / L / XL',
    'inquiry.regionPlaceholder': 'e.g. Europe, North America, Korea',
    'inquiry.brandPlaceholder': 'e.g. Your brand name or independent designer',
    'inquiry.contactPlaceholder': 'e.g. +1 555 000 0000 or email@example.com',
    'inquiry.messagePlaceholder': 'Please describe your specific requirements, fabric preferences, or special requests…',
    'inquiry.submit': 'Send Inquiry',
    'inquiry.sending': 'Sending…',
    'inquiry.success.title': 'Thank You for Your Inquiry',
    'inquiry.success.desc': 'We have received your request and will contact you within 1-2 business days.',
    'inquiry.error': 'Submission failed. Please try again later.',

  },

  ko: {
    // Nav
    'nav.home': '홈',
    'nav.services': '서비스',
    'nav.products': '제품',
    'nav.global': '글로벌',
    'nav.about': '회사소개',
    'nav.contact': '문의하기',

    // Hero
    'hero.label': '글로벌 패션 공급망',
    'hero.line1': '아이디어에서 완성품까지',
    'hero.line2': '유연한 공급망 솔루션',
    'hero.text': '专注冬装外套，整合全球优质资源，让每一个设计创意高效落地',
    'hero.text': '겨울 아우터웨어 전문 — 글로벌 프리미엄 자원을 통합하여 모든 디자인을 현실로',
    'hero.sub': '겨울 아우터웨어 전문 — 글로벌 프리미엄 자원을 통합하여 모든 디자인을 현실로',
    'hero.cta1': '제품 보기',
    'hero.cta2': '문의하기',

    // Products
    'products.label': '핵심 제품',
    'products.title': '겨울 아우터웨어\n4가지 핵심 카테고리',
    'products.subtitle': '기본 스타일부터 맞춤 제작까지 — 다양한 브랜드의 니즈 충족',
    'products.down.title': '다운 재킷 & 아우트도어 시리즈',
    'products.down.keyword': '복잡한 공정 · 신속한 대응',
    'products.down.point1.title': '핵심 강점',
    'products.down.point1.desc': '20년 경험의 패턴 마스터 팀, 구조가 복잡한 전문 스키웨어 및 기능성 아우터 제작 특화.',
    'products.down.point2.title': '글로벌 스탠다드',
    'products.down.point2.desc': '한중일 톱급 공급업체 통합, 모든 트림이 럭셔리 급 기준을 충족하도록 보장.',
    'products.down.point3.title': '애질 제조',
    'products.down.point3.desc': '초저 MOQ로 다른 곳에서 복제할 수 없는 소량 빠른 대응 능력.',
    'products.down.tag1': '복잡한 공정',
    'products.down.tag2': '신속 대응',
    'products.coat.title': '더블 페이스 캐시미어 코트',
    'products.coat.keyword': '장인 정신 · 유연한 공급',
    'products.coat.point1.title': '공정 기준',
    'products.coat.point1.desc': '20년 이상의 장인 팀, 국제 명품 하우스 수준의 바늘따기 기준.',
    'products.coat.point2.title': '빠른 피드백',
    'products.coat.point2.desc': '산업 기지 핵심 자원 활용으로 업계 최빠르는 원단 샘플링 답변.',
    'products.coat.point3.title': '유연한 맞춤 제작',
    'products.coat.point3.desc': '초저 MOQ와 유연한 리드타임 — 디자이너 브랜드의 아이디어를 현실로 만드는 선호 파트너.',
    'products.coat.tag1': '장인 정신',
    'products.coat.tag2': '유연한 공급',
    'products.fur.title': '퍼 & 쉬어링',
    'products.fur.keyword': '산지 기반 · 글로벌 비전',
    'products.fur.point1.title': '산지 우위',
    'products.fur.point1.desc': '중국 하이닝(세계 최대 퍼 기지) 기반, 30년 수직 도메인 전문 경험.',
    'products.fur.point2.title': '전면 맞춤 제작',
    'products.fur.point2.desc': '원자재 소싱부터 디자인 개발까지 — 프리미엄 소재에 대한 모든 브랜드 요구 충족.',
    'products.fur.point3.title': '재고 걸정 제로',
    'products.fur.point3.desc': '경쟁력 있는 유연 생산 모델로 고급 퍼 카테고리의 재고 리스크 제거.',
    'products.fur.tag1': '산지 기반',
    'products.fur.tag2': '글로벌 비전',
    'products.duvet.title': '다운 침구',
    'products.duvet.keyword': '프리미엄 충전 · 럭셔리 컴포트',
    'products.duvet.point1.title': '글로벌 소재',
    'products.duvet.point1.desc': '중국 최대 다운 전략 파트너 활용, 전 세계 수십 종의 고수준 프리미엄 다운 대상.',
    'products.duvet.point2.title': '프라이빗 솔루션',
    'products.duvet.point2.desc': '표준 샘플과 고급 프라이빗 레이블 옵션 제공 — 기술 소재로 수면 미학 재정의.',
    'products.duvet.point3.title': '품격 있는 삶',
    'products.duvet.point3.desc': '최고의 청결도와 평포도, 일상의 최고를 추구하는 고객을 위해 맞춤 제작.',
    'products.duvet.tag1': '프리미엄 충전',
    'products.duvet.tag2': '럭셔리 컴포트',

    // Services
    'services.label': '풀체인 서비스',
    'services.title': '아이디어에서 완성품까지\n모든 단계 커버',
    'services.subtitle': '디자인부터 납품까지 완전한 체인을 커버하는 6가지 핵심 서비스',
    'services.tagline': '모든 아이디어를 완벽한 의류로 실현',
    'services.cta': '지금 문의하기',
    'services.design.title': '디자인 & 샘플링',
    'services.design.desc': '최고 수준의 패턴 마스터와 장인으로 구성된 팀이 3D 디지털 가상 샘플링과 실물 프로토타입 제작을 병행하는 이중 트랙 시스템을 운영합니다. 48시간 이내에 초기 샘플을 완성하여 모든 실루엣 디테일과 공정 요구사항을 정확히 재현하고, 창의적 비전을 최고의 효율로 양산 가능한 솔루션으로 전환합니다.',
    'services.design.point1.title': '3D 가상 샘플링',
    'services.design.point1.desc': 'CLO3D 등 업계 선도 소프트웨어를 활용한 디지털 모델링으로 샘플링 리드타임을 대폭 단축하고, 원자재 낭비를 최소화하며 원격 실시간 검토 및 승인을 지원합니다.',
    'services.design.point2.title': '실물 프로토타입 제작',
    'services.design.point2.desc': '시니어 패턴 마스터가 전 과정을 감독하며, 머슬린 토일에서 최종 원단 샘플까지 단계적으로 정밀하게 다듬어 모든 봉제선과 구조가 브랜드의 납품 기준을 충족하도록 합니다.',
    'services.design.point3.title': '기술 자문 지원',
    'services.design.point3.desc': '전담 기술 자문이 브랜드와 협력하여 디자인 디테일을 최적화하고, 미적 비전을 유지하면서 생산 실현 가능성과 비용 효율성을 향상시킵니다.',
    'services.design.tag1': '3D 디지털 샘플링',
    'services.design.tag2': '48H 신속 대응',
    'services.sampling.title': '브랜드 인큐베이션',
    'services.sampling.desc': '신흥 브랜드 및 디자이너에게 브랜드 포지셔닝 전략, 상표 등록, 비주얼 아이덴티티 시스템 디자인, 제품 라인 기획, 패키지 개발, 멀티채널 판매 프로모션을 아우르는 엔드투엔드 인큐베이션 솔루션을 제공합니다. 전문 리소스 네트워크를 통해 최단 시간 내 시장 출시를 실현합니다.',
    'services.sampling.point1.title': '브랜드 전략 기획',
    'services.sampling.point1.desc': '목표 시장 및 경쟁 환경에 대한 심층 조사를 통해 브랜드의 정확한 포지셔닝, 사용자 페르소나 구축, 차별화된 가치 제안 도출을 지원합니다.',
    'services.sampling.point2.title': '비주얼 & 패키지 디자인',
    'services.sampling.point2.desc': '브랜드 로고, 핵심 비주얼, 행택, 패키지 등 전체 비주얼 에셋 디자인을 제공하여 모든 소비자 접점에서 브랜드 톤앤매너의 일관성을 보장합니다.',
    'services.sampling.point3.title': '채널 론칭 지원',
    'services.sampling.point3.desc': '국내외 주요 이커머스 플랫폼 및 바이어 채널과의 연결을 통해 상품 기획, 스토어 운영, 마케팅 캠페인에 대한 전문적인 가이드를 제공합니다.',
    'services.sampling.tag1': '풀체인 인큐베이션',
    'services.sampling.tag2': '브랜드 전략',
    'services.production.title': '유연 생산',
    'services.production.desc': '엄격한 자격 심사를 통과한 2000개 이상의 파트너 공장 연합을 기반으로 업계 선도적인 유연 생산 시스템을 구축했습니다. 100개부터 소량 주문을 지원하며, 표준 스타일은 15~25일 이내에 납품됩니다. 전체 공급망 디지털 관리를 통해 모든 생산 마일스톤의 완전한 투명성을 보장합니다.',
    'services.production.point1.title': '소량 신속 대응',
    'services.production.point1.desc': '최소 100개 주문으로 기존 공장의 높은 MOQ 장벽을 허물어, 브랜드가 최소한의 재고 리스크로 시장을 검증하고 제품 라인을 빠르게 반복할 수 있도록 합니다.',
    'services.production.point2.title': '엄선된 공장 연합',
    'services.production.point2.desc': '엄격한 자격 심사를 통과한 2000개 이상의 파트너 공장이 다운, 아우터웨어, 퍼 등 세부 카테고리를 커버하며, 각 주문의 특정 생산 능력 요구사항에 맞게 지능적으로 매칭됩니다.',
    'services.production.point3.title': '전체 공급망 시각화',
    'services.production.point3.desc': '자체 개발한 주문 추적 시스템으로 재단, 봉제, 마감, 출고까지 모든 생산 노드에서 실시간 보고가 이루어져 고객이 언제든지 진행 상황을 모니터링할 수 있습니다.',
    'services.production.tag1': '100개부터 주문',
    'services.production.tag2': '15~25일 납품',
    'services.fabric.title': '원단 조달',
    'services.fabric.desc': '중국, 일본, 한국, 유럽, 이탈리아 등 주요 섬유 생산 지역의 500개 이상 세계 최고 수준의 원단 공급업체와 장기 전략적 파트너십을 유지합니다. 원단 R&D, 맞춤 개발, 샘플 제작부터 제3자 검사 인증까지 원스톱 서비스를 제공하여 모든 소재가 브랜드의 품질 기준과 지속 가능성 요건을 충족하도록 합니다.',
    'services.fabric.point1.title': '글로벌 원단 라이브러리',
    'services.fabric.point1.desc': '중국, 일본, 한국, 이탈리아의 프리미엄 원단 리소스를 집약하여 다운 원단, 더블 페이스드 캐시미어, 퍼, 기능성 소재 등 수천 개의 SKU를 커버합니다.',
    'services.fabric.point2.title': '맞춤 개발 서비스',
    'services.fabric.point2.desc': '전용 원사 배합, 커스텀 직조 구조, 특수 후가공 공정을 포함한 브랜드 전용 원단 개발을 지원하여 타의 추종을 불허하는 소재 차별화를 창출합니다.',
    'services.fabric.point3.title': '검사 및 인증 지원',
    'services.fabric.point3.desc': 'SGS, Bureau Veritas 등 국제 공인 검사 기관과 협력하여 섬유 성분, 색견뢰도, 수축률 등에 대한 종합 보고서를 제공하여 글로벌 시장 진입 요건을 충족합니다.',
    'services.fabric.tag1': '500개 이상 공급업체',
    'services.fabric.tag2': '글로벌 직접 소싱',
    'services.quality.title': '품질 보증',
    'services.quality.desc': '원자재 입고 검사부터 공정 내 품질 관리, 최종 출하 전 검사까지 전체 생산 체인에 걸친 12단계 전문 품질 검사 시스템을 구축했습니다. 각 단계마다 전담 QC 인력이 관리하며, 디지털화된 품질 관리 시스템이 완전히 추적 가능한 검사 보고서를 생성하여 모든 완성 의류에 검증 가능한 품질 보증을 제공합니다.',
    'services.quality.point1.title': '입고 품질 관리 (IQC)',
    'services.quality.point1.desc': '원단 색차, 중량, 섬유 성분, 부자재 사양 등 모든 입고 원자재 및 부자재에 대한 엄격한 검사를 실시하며, 부적합 자재는 예외 없이 반품 처리합니다.',
    'services.quality.point2.title': '공정 품질 관리 (IPQC)',
    'services.quality.point2.desc': '재단, 봉제, 마감 등 핵심 생산 단계에 품질 관리 체크포인트를 설정하여 실시간 샘플링 검사와 즉각적인 시정 조치를 통해 불량품을 생산 과정에서 제거합니다.',
    'services.quality.point3.title': '최종 품질 검사 (FQC)',
    'services.quality.point3.desc': '치수 사양, 외관 품질, 포장 기준을 포함한 종합적인 출하 전 검사를 실시하며, 각 출하물과 함께 완전한 검사 보고서를 제공합니다.',
    'services.quality.tag1': '12단계 검사',
    'services.quality.tag2': '완전 추적 가능',
    'services.logistics.title': '물류 & 배송',
    'services.logistics.desc': '해상 운송, 항공 운송, 특급 배송, 현지 라스트마일 배송을 통합한 엔드투엔드 국제 물류 솔루션을 제공합니다. DHL, FedEx 등 글로벌 선도 운송사와의 우선 파트너십으로 다목적지 분할 발송을 지원하며, 자체 개발한 물류 추적 플랫폼을 통해 공장 출고부터 고객 수령까지 실시간 전체 공급망 가시성을 제공합니다.',
    'services.logistics.point1.title': '복합 운송 솔루션',
    'services.logistics.point1.desc': '주문 리드타임과 비용 요건에 따라 FCL/LCL 해상 운송, 항공 운송, 특급 배송의 최적 조합을 지능적으로 매칭하여 전 세계 주요 목적지 항구를 커버합니다.',
    'services.logistics.point2.title': '해외 창고 지원',
    'services.logistics.point2.desc': '한국 서울에 자체 창고 센터를 운영하여 현지 배송, 반품 처리, 크로스보더 이커머스 풀필먼트를 지원하고 라스트마일 배송 비용을 효과적으로 절감합니다.',
    'services.logistics.point3.title': '실시간 추적 플랫폼',
    'services.logistics.point3.desc': '자체 개발한 물류 시각화 플랫폼으로 공장 출고부터 고객 서명까지 모든 체인 노드에서 실시간 업데이트를 제공하며, 다국어 알림을 지원하여 화물 동향을 완전히 파악할 수 있습니다.',
    'services.logistics.tag1': '글로벌 복합 운송',
    'services.logistics.tag2': '실시간 추적',

    // Global Presence
    'global.label': '글로벌 네트워크',
    'global.title': '항저우에서 시작하여\n서울 첫 해외 지사',
    'global.subtitle': '국제적 운영, 현지화 서비스',
    'global.hq': '본사',
    'global.branch': '해외 지사',
    'global.label': '全球布局',
    'global.title': '立足杭州 首尔为首个海外分部',
    'global.subtitle': '国际化运营，本地化服务',
    'global.hangzhou': '杭州',
    'global.seoul': '首尔',
    'global.hz.status': '中国总部',
    'global.kr.status': '韩国分部',
    'global.hz.desc': '中国服装供应链核心枢纽，整合长三角优质制造资源',
    'global.kr.desc': '韩国时尚之都，连接东亚顶级设计师与品牌资源',
    'global.hangzhou.city': '항저우',
    'global.hangzhou.desc': '중국 의류 공급망의 핵심 허브, 양쯔강 삼각주 프리미엄 제조 자원 통합',
    'global.seoul.city': '서울',
    'global.seoul.desc': '한국 패션의 수도, 동아시아 최고의 디자이너 및 브랜드 자원 연결',
    'global.expanding': '진출 예정',
    'global.tokyo': '도쿄',
    'global.paris': '파리',
    'global.newyork': '뉴욕',
    'global.milan': '밀라노',
    'global.address': '주소',
    'global.phone': '전화',
    'global.email': '이메일',
    'global.hours': '시간',
    'global.upcoming': '입점 예정',

    // About
    'about.label': '회사소개',
    'about.title': '우리는 누구인가',
    'about.subtitle': '글로벌 패션 공급망의 혁신자',
    'about.story.title': '패션 공급망을 재정의하다: SAMPLE & SIMPLE',
    'about.story.text': '저희는 패션과 탁월한 제조에 대한 끊임없는 추구에서 탄생했습니다. 전통적인 공급망이 디자인에 가하는 제약을 타파하기 위해, 창의성과 생산을 연결하는 글로벌 유연 플랫폼을 구축했습니다. 공급망의 유연성을 브랜드의 핵심 차별화 가치로 전환하는 데 전념합니다.\n\n플랫폼은 서울 지사의 패션 소싱 역량과 항저우 공급망 본사의 제조 역량을 깊이 통합하여, 다운 재킷, 더블 페이스 울 코트, 프리미엄 쉬어링의 풀서비스 솔루션에 특화되어 있습니다. 한중일 최고급 원부자재 자원을 연결하여 최소 주문량 100개의 친화적인 대량 생산 모드를 실현하고, 브랜드의 재고 및 판매 압박을 최소화합니다.\n\n정밀 샘플링부터 대규모 생산까지 전 과정에 걸쳐 엄격한 품질 기준을 유지하며, 전 세계 프리미엄 및 럭셔리 브랜드에 원스톱 JDM 솔루션을 제공합니다. 탁월한 국경 간 대응 능력으로 모든 브랜드가 영감을 완벽하게 실현하고 탁월한 성장을 달성할 수 있도록 지원합니다.',
    'about.brand.hz': 'RONDA — 항저우',
    'about.brand.kr': 'ATLY — 서울',
    'about.digital': '디지털 우선',
    'about.digital.desc': '모든 주문의 생산 현황을 실시간으로 확인할 수 있는 전체 공급망 디지털 관리',
    'about.talent': '최고의 인재',
    'about.talent.desc': '패션, 공급망, 디자인 분야의 베테랑 전문가들로 구성',
    'about.global': '글로벌 비전',
    'about.global.desc': '항저우에 기반을 두고 서울로 확장하며 글로벌 프리미엄 자원과 시장 연결',
    'about.sustainable': '지속 가능성',
    'about.sustainable.desc': '친환경 원단과 지속 가능한 생산 공정을 통해 브랜드 ESG 목표 지원',
    'stats.years': '년 업계 경험',
    'stats.years.val': '10+',
    'stats.years.unit': '년',
    'stats.factories': '협력 공장',
    'stats.factories.val': '2000+',
    'stats.fabrics': '원단 공급업체',
    'stats.fabrics.val': '500+',
    'stats.moq': '최소 주문량',
    'stats.moq.val': '100개',
    'stats.team': '전문 팀',
    'stats.team.unit': '명',
    'stats.output': '연간 생산량',
    'stats.output.unit': '만 개',
    'stats.countries': '진출 국가',
    'stats.countries.unit': '개',

    // Contact
    'contact.label': '문의하기',
    'contact.title': '세계 어디에 계시든\n저희가 도와드리겠습니다',
    'contact.subtitle': '언제든지 문의해 주세요',
    'contact.hangzhou': '항저우 본사 · RONDA',
    'contact.seoul': '서울 지사 · ATLY',
    'contact.hz.phone': '0571-88012309',
    'contact.hz.email': 'zylen@samplewear.com',
    'contact.hz.address': '항저우시 시후구 루이보 국제빌딩 B동 1707호',
    'contact.hz.time': '월–금 9:00–18:00',
    'contact.hz.hours': '월–금 9:00–18:00',
    'contact.kr.phone': '02 6956 9855',
    'contact.kr.email1': 'kimsih6068@naver.com',
    'contact.kr.email2': 'guangmdc0901@gmail.com',
    'contact.kr.address': '서울특별시 마포구 동교동 174 정하빌딩 5층',
    'contact.kr.time': '월–금 9:00–18:00',
    'contact.kr.hours': '월–금 9:00–18:00',
    'contact.form.name': '성함',
    'contact.form.phone': '전화번호',
    'contact.form.email': '이메일',
    'contact.form.service': '서비스 유형',
    'contact.form.service.placeholder': '서비스를 선택하세요',
    'contact.form.service.down': '다운 재킷 맞춤 제작',
    'contact.form.service.coat': '코트 맞춤 제작',
    'contact.form.service.fur': '쉬어링 맞춤 제작',
    'contact.form.service.duvet': '다운 이불 맞춤 제작',
    'contact.form.service.other': '기타',
    'contact.form.message': '요구사항을 자세히 설명해 주세요...',
    'contact.form.submit': '문의 제출',
    'contact.form.sent': '접수되었습니다! 곧 연락드리겠습니다.',
    'contact.social.title': '소셜 미디어',
    'contact.im.title': '메신저',
    'contact.scan': '스캔하여 팔로우',
    'contact.click': '클릭하여 연결',

    // Footer
    'footer.tagline': '글로벌 패션 공급망 플랫폼',
    'footer.rights': '© 2025 Sample & Simple. All rights reserved.',
    'footer.privacy': '개인정보 처리방침',
    'footer.nav.products': '제품',
    'footer.nav.services': '서비스',
    'footer.nav.global': '글로벌',
    'footer.nav.about': '회사소개',
    'footer.nav.contact': '문의하기',
    'footer.offices': '글로벌 오피스',
    'footer.company.label': '회사 정보',
    'footer.company.name': '항저우 롱다 테크놀로지',
    'footer.nav.label': '내비게이션',
    'footer.follow': '팔로우',
    'footer.terms': '서비스 약관',
    'footer.icp': '浙ICP备2025188038号-1',
    // Sample App Section
    'sampleapp.label': '디지털 플랫폼',
    'sampleapp.title': '세계 최고의 동복 디지털 공급망 플랫폼',
    'sampleapp.slogan': '더 간단하게 · 더 편리하게 · 더 정확하게',
    'sampleapp.availability': 'Sample App은 현재 중국에서 출시되었으며, 글로벌 버전은 곧 주요 앱스토어에 출시될 예정입니다.',
    'sampleapp.slide1.title': '우리의 포지셔닝',
    'sampleapp.slide1.subtitle': '글로벌 창의성과 중국 최고 제조업을 연결하는 디지털 브릿지',
    'sampleapp.slide1.desc': 'Sample은 프리미엄 동복(다운재킷, 더블페이스 코트, 모피)의 원스톱 맞춤 서비스를 전문으로 합니다. 독립 디자이너와 브랜드 오너가 국경을 넘어 사무실에서 샘플 개발부터 대량 납품까지 전 과정을 완료할 수 있습니다.',
    'sampleapp.slide1.tag1': '최소 100개',
    'sampleapp.slide1.tag2': '엔드투엔드 디지털',
    'sampleapp.slide2.title': '완전한 투명성',
    'sampleapp.slide2.subtitle': '디지털 진행 추적으로 소통 사각지대 완전 해소',
    'sampleapp.slide2.desc': '샘플 생산 완료, 물류 정보 업로드, 수령 확인까지 모든 단계가 실시간으로 동기화됩니다. 국제 물류 전 과정 가시화로 어디서든 모든 주문을 완벽히 파악할 수 있습니다.',
    'sampleapp.slide2.tag1': '실시간 추적',
    'sampleapp.slide2.tag2': '국제 물류 동기화',
    'sampleapp.slide3.title': '진행 보고',
    'sampleapp.slide3.subtitle': '생산 진행 상황 실시간 보고, 투명하고 관리 가능',
    'sampleapp.slide3.desc': '공장은 자재 준비, 샘플 제작, 생산 완료의 세 가지 주요 단계에서 진행 사진을 업로드합니다. 모든 단계가 기록됩니다. 제3자 전문 품질 검사와 주문 보험 시스템으로 국제 거래의 안전과 품질을 보장합니다.',
    'sampleapp.slide3.tag1': '품질 보증',
    'sampleapp.slide3.tag2': '주문 보험',
    'sampleapp.slide4.title': '온라인 맞춤 제작',
    'sampleapp.slide4.subtitle': '4단계로 완성하는 샘플 맞춤 제작, 전문적이고 효율적',
    'sampleapp.slide4.desc': '스타일 유형, 샘플 앞뒤면, 원단 및 부자재, 수량 설정 — 4단계 가이드 프로세스로 전문 샘플 맞춤 제작을 손쉽게 완료합니다. 참고 이미지를 업로드하고 수정 요청을 입력하면 플랫폼이 최적의 공장 리소스를 자동으로 매칭합니다.',
    'sampleapp.slide4.tag1': '4단계 프로세스',
    'sampleapp.slide4.tag2': 'AI 스마트 매칭',
    'sampleapp.slide5.title': '개인 대시보드',
    'sampleapp.slide5.subtitle': '샘플 플랜, 주문 관리, 기업 인증을 한 곳에서',
    'sampleapp.slide5.desc': '개인 대시보드는 샘플 플랜, 샘플 주문, 대량 주문의 세 가지 모듈을 통합하며 기업 인증 및 세금계산서 관리를 지원합니다. 인증 사용자는 전담 고객 서비스와 우선 생산 일정 배정 혜택을 누립니다.',
    'sampleapp.slide5.tag1': '기업 인증',
    'sampleapp.slide5.tag2': '전담 지원',
    'sampleapp.feature1.icon': '⬡',
    'sampleapp.feature1.title': '소량 주문',
    'sampleapp.feature1.desc': '최소 100개부터, 빠른 회전, 재고 부담 없이 시장 검증',
    'sampleapp.feature2.icon': '◎',
    'sampleapp.feature2.title': '전 과정 추적',
    'sampleapp.feature2.desc': '디지털 대시보드로 모든 단계 실시간 가시화',
    'sampleapp.feature3.icon': '◈',
    'sampleapp.feature3.title': '안전 납품',
    'sampleapp.feature3.desc': '제3자 품질검사 + 주문 보험으로 국제 거래 걱정 없음',
    'sampleapp.ai.label': 'THE FUTURE IS AI',
    'sampleapp.ai.title': 'AI 기반 디지털 비전',
    'sampleapp.ai.point1': 'AI 보조 디자인 — AI 트렌드 분석 및 디자인 생성 도구 출시 예정, 창의성을 생산력으로 전환',
    'sampleapp.ai.point2': '3D 가상 피팅 — AI 모델링 기술 개발로 고품질 온라인 피팅 실현, 물리적 샘플링 주기와 비용 대폭 절감',
    'sampleapp.ai.point3': '글로벌 협업 — 전용 맞춤 데이터베이스 구축으로 "글로벌 디자인, 중국 제조, 세계 서비스"의 무한 협업 모드 실현',
    // Inquiry Form
    'inquiry.title': 'INQUIRY',
    'inquiry.heading': '샘플 & 주문 문의',
    'inquiry.subheading': '아래 정보를 입력해 주시면 1-2 영업일 내에 연락드리겠습니다.',
    'inquiry.back': '홈으로 돌아가기',
    'inquiry.sampleType': '샘플 유형',
    'inquiry.hasSample': '참고 샘플이 있으신가요?',
    'inquiry.expectedQty': '예상 주문 수량',
    'inquiry.color': '색상 요구사항',
    'inquiry.size': '사이즈 범위',
    'inquiry.region': '지역',
    'inquiry.brand': '브랜드명',
    'inquiry.contact': '연락처',
    'inquiry.message': '추가 메모',
    'inquiry.select': '선택해 주세요',
    'inquiry.yes': '있음',
    'inquiry.no': '없음',
    'inquiry.qtyPlaceholder': '예: 100개 (최소 주문 수량)',
    'inquiry.colorPlaceholder': '예: 오프화이트, 블랙, 네이비',
    'inquiry.sizePlaceholder': '예: S / M / L / XL (아시아 사이즈)',
    'inquiry.regionPlaceholder': '예: 한국, 일본, 유럽',
    'inquiry.brandPlaceholder': '예: 브랜드명 또는 개인 디자이너',
    'inquiry.contactPlaceholder': '예: +82 10 0000 0000 또는 email@example.com',
    'inquiry.messagePlaceholder': '구체적인 요구사항, 원단 선호도 또는 특별 요청사항을 설명해 주세요…',
    'inquiry.submit': '문의 보내기',
    'inquiry.sending': '전송 중…',
    'inquiry.success.title': '문의해 주셔서 감사합니다',
    'inquiry.success.desc': '요청을 받았으며 1-2 영업일 내에 연락드리겠습니다.',
    'inquiry.error': '제출에 실패했습니다. 나중에 다시 시도해 주세요.',

  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[lang][key] || translations['zh'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
